### ISSUE TITLE
Lot numbers not unique, missing in Tracking workbook

### ISSUE THREAD

**Issue by pekka-28** [Makespace/visor#1]
I have tried to analyse some of the data in the Tracking workbook and found a number of data items that don't make sense.

There are several Lot numbers that are duplicated in the workbook in adjacent to each other. The timing is around a minute apart, and the workstation is the same. This looks to be duplicated data capture. I'm not clear whether the number if meant to be a primary key, or some kind of rough relative ordering indicator so can't say if this is significant.

I also note that several of the Void workstation lots have a dependency with the value -1. Since this lot does not exist in the database, I noticed this in a foreign key relationship error.

After some massaging, I created the attached image for the first day of data. This could be helpful in understanding non-standard operation sequences in the event of problems. For example, it looks like the Boxing node is using the incorrect traceability lot information.

![Operation sequence](https://user-images.githubusercontent.com/4647573/79372857-606ea380-7f56-11ea-886a-3c5dc352b861.png)

**Comment by axiomsofchoice** [comment]
The data in the `JobLog` sheet of `Tracking - Workers, Goods, Jobs.xlsx` represents an early snapshot of the data. It's important to understand how these data were collected. Originally there was just a spreadsheet but it rapidly became clear that errors would easily creep in so a [web app](https://github.com/axiomsofchoice/jobcardsystem) was created to eliminate these as far as possible. For instance, making it only possible to select up-stream job cards that were both of the right type and still marked as WIP. Over time this improved data quality but some manual intervention was still required at times. For a while we saw double entries because the Google servers were slow to response so users clicked until they received a response. Duplicates were marked `Void`, as documented [here](https://github.com/axiomsofchoice/jobcardsystem#guidance-for-admins). This artifact was eliminated by disabling the submit button after the first click. As part of the [`reporting.py`](https://github.com/axiomsofchoice/jobcardsystem#reporting) tool it's possible to discover exactly the inconsistencies in dependencies you highlight here and manually fix them.  Now that production has finished it's possible to provide an updated version with the issues you've identified fixed and I'll ask if this is possible, following appropriate anonymization. I'm impressed with the graph you've come up with! Those dependencies should really look like [this](https://github.com/axiomsofchoice/jobcardsystem/blob/dc2df42d65eb95329684bf60aed9f6e3ece49720/reporting/reporting.py#L57). If you like graphs why not try `reporting.py --graph` and please share any results of analyses you come up with :)

**Comment by pekka-28** [comment]
That is much what expected. I see the Python code also uses Graphviz for the rendering. I have used the [ProM process mining toolkit ](http://www.promtools.org/doku.php) for this kind of analysis in the past. One of the helpful use cases is that the tool can identify uncommon flows. This usually indicates a work-around in a production environment and is often worth investigation.

**Comment by axiomsofchoice** [comment]
I wasn't aware of that toolkit. Thanks for sharing!
